modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = "A valid URL to your issue tracker where people can open bug tickets"
license = "MIT License"

[[mods]]
modId = "cobblemon_raids"
version = "${version}"
displayName = "Cobblemon:Raids"
authors = "Me!"
description = '''

'''
#logoFile = ""

[[dependencies.cobblemon_raids]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_raids]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.66,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_raids]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "mixins.cobblemon_raids-common.json"
[[mixins]]
config = "mixins.cobblemon_raids-neoforge.json"